name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  TestSanity:
    runs-on: ubuntu-latest
    container: python
    steps:
      - uses: actions/checkout@v2
      - name: SanityCheck
        run: |
          pip install -r requirements.txt
          pip install -r test-requirements.txt
          pytest test/test_sanity.py
  TestHello:
    runs-on: ubuntu-latest
    container: python
    steps:
      - uses: actions/checkout@v2
      - name: TestHello
        run: |
          pip install -r requirements.txt
          pip install -r test-requirements.txt
          pytest test/test_hello.py
  TestGoodbye:
    runs-on: ubuntu-latest
    container: python
    steps:
      - uses: actions/checkout@v2
      - name: TestGoodbye
        run: |
          pip install -r requirements.txt
          pip install -r test-requirements.txt
          pytest test/test_goodbye.py
  RunAllTests:
    runs-on: ubuntu-latest
    container: python
    steps:
      - uses: actions/checkout@v2
      - name: RunAllTests
        run: |
          pip install -r requirements.txt
          pip install -r test-requirements.txt
          pytest
